# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='network',
        ),
        migrations.AddField(
            model_name='network',
            name='matrixX',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AddField(
            model_name='network',
            name='result',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AddField(
            model_name='network',
            name='runtime',
            field=models.IntegerField(default=10000, max_length=255),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
